### ISSUE TITLE
Use hugo for building website?

### ISSUE THREAD

**Issue by IRus** [ktorio/ktorio.github.io#161]
Hi! I'd like to migrate full site to hugo, so it will build faster and much simpler for website authors (since hugo distributing as single binary).

What your opinion on this?

**Comment by cy6erGn0m** [comment]
For experienced jekyll related build issues however it has been fixed so now it works sufficient. The value of migration to Hugo is not that obvious, at least not after a quick overview. Could you please explain it?

**Comment by IRus** [comment]
1. Build time (I didn't checked latest changes in [docker-run-develop.sh](https://github.com/ktorio/ktorio.github.io/blob/master/docker-run-develop.sh)), but before initial startup time was giant. Hugo famous for its build time, my blog with 200 articles builds in second;
2. Docker or Ruby for development, I'm pretty OK with docker, but single binary which hugo provides much easier to user.

For me that it: developer experience.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-284">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
