### ISSUE TITLE
Ktor Doc

### ISSUE THREAD

**Issue by mirjalolbahodirov** [ktorio/ktorio.github.io#2]
Hello, Ktor Team! 
Firstly, I'd like to thank you for creating such a great framework!
Nowadays, I need to create my next new project and I decided to using Kotlin language.
So, I researched over frameworks(libs) such as Spring 5, Vert.x, Ktor and more...
I know Spring Framework and Vert.x, but Ktor is young framework. I prefer to coding like Ktor style. My question is: can I use Ktor for my current and  future projects? As I see, documentation is not completed totally. When you are planning to finish full doc?
Any ideas will be appreciated highly!
Thank you!

**Comment by orangy** [comment]
Documentation is not completed, and ktor is not even 1.0 yet, so you'll need to decide it yourself if it works for you. We are working on docs, and API is changing from time to time (we try to keep migration path whenever feasible), so if you expect stable battle tested framework, you might consider other options. But we react fast and fix bugs as soon as possible, so if you are brave enough, welcome to ktor :)

**Comment by mirjalolbahodirov** [comment]
I got you, thank you for attention and quick answer!
