### ISSUE TITLE
Can I create a SOAP service with Ktor?

### ISSUE THREAD

**Issue by ZwiiDoan** [ktorio/ktorio.github.io#203]
Looking at ktor as an alternative to spring boot and wondering if I can migrate my SOAP Service s built by Spring Boot to ktor?

**Comment by cy6erGn0m** [comment]
ktor doesn't provide any generation for now so one would need to do too much work to get _true_ SOAP working including WSDL generation

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-277">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
