### ISSUE TITLE
How to use mqtt in Ktor missing ktor doc.

### ISSUE THREAD

**Issue by Arthur-Kamau** [ktorio/ktorio.github.io#259]
## Documentation missing
How do i accept mqtt connection in ktor.
How to set up a mqtt broker in kotlin.
Cannot find an example online

**Comment by martinbeentjes** [comment]
Hi @Arthur-Kamau, as MQTT is a messaging protocol I assume there must be some Kotlin library to find online. I've googled for _"kotlin mqtt client"_ and I [got](https://gist.github.com/hussanhijazi/4fd7c737ccb4f1006ad2e36f3108ddccl) (plenty|https://github.com/thebehera/mqtt) (results|https://medium.com/@chaitanya.bhojwani1012/eclipse-paho-mqtt-android-client-using-kotlin-56129ff5fbe7). 

How weren't you able to find an example online that you can work with?

Good luck!

**Comment by Arthur-Kamau** [comment]
At the time was more interested in  integrating server side mqtt with something like VernMQ or RabbitMq.
For example with Websockets there are detailed example on how to accept websocket connection and respond tot the and finally close them.I was looking forward to such a step by step guide in the docs.
Thanks.

**Comment by martinbeentjes** [comment]
As the documentation is open source, feel free to write such documentation yourself and help each other out! 😃

**Comment by Arthur-Kamau** [comment]
Okay thanks.
