### ISSUE TITLE
Clicking "Also On" link redirects to http://0.0.0.0:4000

### ISSUE THREAD

**Issue by goreRatzete** [ktorio/ktorio.github.io#4]
When I click one of the "ALSO ON KTORIO.GITHUB.IO" links, I get redirected to `http://0.0.0.0:4000/getting-started-IDEA-Gradle.html` or similar. 

Hovering over the link reveals this:
```
http://disq.us/url?url=http%3A%2F%2F0.0.0.0%3A4000%2Fgetting-started-IDEA-Gradle.html%3ARQCJjCtpSlWcH9qINlYDInUGU8M&imp=2hhb82l1qfbos7&prev_imp=2hh7ell1269c05&forum_id=5179881&forum=ktorio-github-io&thread_id=5988522479&user_id=203723480&thread=5988553209&zone=thread&area=bottom&object_type=thread&object_id=5988553209
```

**Comment by hhariri** [comment]
Fixed thanks. In fact the "ALSO ON" shouldn't have been activated since it's using Disqus's topic recommendation which can confuse since sometimes the specific topic has no relation.
