### ISSUE TITLE
Sensible docker configuration

### ISSUE THREAD

**Issue by adhesivee** [ktorio/ktorio.github.io#65]
I have some remarks about the docker configuration on https://github.com/ktorio/ktorio.github.io/blob/master/servers/deploy.md

I think the configuration -Xms4g and -Xmx4g are overkill. 
Also the jar is added under the root user, which is security wise not the best solution.

I understand these are examples, but I think the example can be better.

**Comment by soywiz** [comment]
Let me know if these changes addresses your concerns: https://github.com/ktorio/ktorio.github.io/commit/ff5ae01291151bb78aa8ec49617340aab46e6e51

**Comment by adhesivee** [comment]
Looks great
